db-uri = "postgres://authenticator:change-me@localhost:5432/nutriverse"
db-schemas = "api,public"
db-anon-role = "web_anon"
server-host = "127.0.0.1"
server-port = 3000
openapi-mode = "follow-privileges"
